package com.company.prodamgarage;

public enum SceneType {

    ROOT,
    SPLASH,
    MENU,
    GAME,
    MESSAGE,
    NOTIFICATION,
    SELECTION,
    PLAYER_INFO,
    BACK,
    POSSIBILITIES,
    POSSIBILITIES_MENU,
    BUSINESS_POSSIBILITIES,
    BUSINESS_POSSIBILITIES_UNIT,
    APARTMENT_POSSIBILITIES,
    EDUCATION_POSSIBILITIES,

}
